name: gh-pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: importantimport/.github/.github/workflows/pnpm-gh-pages-artifact.yml@main
    with:
      node-version: 22 # https://github.com/fuma-nama/fumadocs/issues/1021
      build: pnpm -r build
      path: docs/dist
